#!/bin/bash

set -eu

: "${AWS_ACCOUNT:=$(aws sts get-caller-identity --output text | awk '{print $1}')}"
: "${AWS_DEFAULT_REGION:=us-east-1}"
: "${AWS_REGION:=${AWS_DEFAULT_REGION}}"

: "${TERRAFORM_WORKSPACE:='default'}"
if test "$#" -eq 1; then
  TERRAFORM_WORKSPACE="${1}"
fi

echo "Using Terraform workspace '${TERRAFORM_WORKSPACE}'"

terraform fmt -check -recursive
terraform init -backend-config "backends/${AWS_ACCOUNT}-${AWS_REGION}.tf" -reconfigure
terraform workspace select "${TERRAFORM_WORKSPACE}" 2>&- || terraform workspace new "${TERRAFORM_WORKSPACE}"
terraform validate
