#!/bin/bash
# shellcheck disable=SC2086

set -eu

: "${AWS_ACCOUNT:=$(aws sts get-caller-identity --output text | awk '{print $1}')}"
: "${AWS_DEFAULT_REGION:=us-east-1}"
: "${AWS_REGION:=${AWS_DEFAULT_REGION}}"

color="-no-color"
tty -s && color=""

terraform plan -out plan.out ${color} "$@" | tee plan.log